### ISSUE TITLE
Time stamp always in 1970

### ISSUE THREAD

**Issue by thebuleon29** [SiriDB/siridb-http#21]
Hi,
I am inserting data into a database with a ms precision on the time stamp, but when I query this data using siridb-http it tells me all my points are in 01-1970.
For example, my first time stamp value is 1516367884386. The website https://currentmillis.com tells me it corresponds to the date Fri Jan 19 2018 13:18:04, so my time stamp is supposed to be correct. However, all the dates are in 1970 in siridb-http.

**Comment by thebuleon29** [comment]
The command "show time_precision" confirms that my database is supposed to have a ms precision.

**Comment by joente** [comment]
Strange, do you see this behavior in charts only? Or do you see this too when you ask for a series "end" time, for example using: `list series name, end "your_series_name"`?

**Comment by thebuleon29** [comment]
Yup, I even have values in 1969 apparently

**Comment by joente** [comment]
Did you try to restart siridb-http? The time-precision of the database should be detected when siridb-http starts. 

I'm not sure how to re-produce your issue. For some reason a `ms` database works as expected, at least on my computer. For example, inserting this data:
```
{
	"series-001": [
		[1516367884386, 42]
	]
}
```

Gives back the expected result:
![Opera Snapshot_2019-04-17_151247_0 0 0 0](https://user-images.githubusercontent.com/6572730/56290826-4e300e80-6124-11e9-9ce9-8a60fe98a887.png)

**Comment by thebuleon29** [comment]
Yes I tried, it doesn't work. When I use `select * from "series"`, I can see the actual timestamp and it is not what I inserted.  The first one for example is 1795731796.

**Comment by joente** [comment]
Can you help me how to re-produce this issue? How did you insert the data?, Did you use the siridb-http insert page, or something else? 

You could also try [siridb-prompt](https://github.com/SiriDB/siridb-prompt/releases) to return the raw value in a terminal, for example: 
```shell
# change username, password, dbname, localhost and series-001 according to your use case
siridb-prompt \
-u username \
-p password \
-d dbname \
-s localhost \
--json \
-r " list series name, end 'series-001' "
```
And this should return something like this:
```
{"columns":["name","end"],"series":[["series-001",1516367884386]]}
```

**Comment by joente** [comment]
@thebuleon29, can you explain how to reproduce the problem, step by step?

**Comment by thebuleon29** [comment]
Step 1 : run SiriDB and SiriDB-HTTP
Step 2 : `curl -u iris:siri -H "Content-Type: application/csv" -X POST localhost:5050/insert --data-binary @file.csv`
Step 3 : the dates are in 1970

**Comment by joente** [comment]
Thanks for the information, maybe this is a 32bit issue? I'm testing mainly on a 64bit system with `siridb-http_2.0.9_linux_amd64.bin`. Which version of SiriDB HTTP are you using?

I've created a `test.csv` file with the following data:
```
"series-001",1556097273000,3.14
```

Then used curl + siridb http to insert the csv data:
```
curl -u iris:siri -H "Content-Type: application/csv" -X POST localhost:8888/insert --data-binary @
```

And used siridb prompt to verify the insert:
```
siridb-prompt -u iris -p siri -d dbtest -s localhost -r " select * from 'series-001' "
```
This is the result:
```
# series-001
timestamp                     ┃ value
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━
Wed Apr 24 11:14:33 CEST 2019 │ 3.14
```

And the time precision, just to be sure:
```
$ siridb-prompt -u iris -p siri -d dbtest -s localhost -r " show time_precision "

name           ┃ value           
━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━
time_precision │ ms (millisecond)
```

I've setup SiriDB HTTP using the following configuration file:
```
[Database]
user = iris
password = siri
dbname = dbtest
servers = localhost:9000

[Configuration]
port = 8888
require_authentication = True
enable_socket_io = True
enable_ssl = False
enable_web = True
enable_basic_auth = True
enable_multi_user = True
cookie_max_age = 604800
insert_timeout = 60
```

**Comment by thebuleon29** [comment]
Hi,
I cloned the siridb-server repository and compiled it myself. 
I just checked and the siridb-http and siridb-prompt binaries I use and they are 64 bit.
My siridb-http config file looks just as yours.
My db time precision is ms as well.

**Comment by joente** [comment]
Can you provide me your `file.csv`? Or just a few rows of your data? (Only if this is not an issue of course)

**Comment by thebuleon29** [comment]
I can't give you the original data, but here is some dummy data I made from my CSV. I did not change the timestamps.
```

benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric1,1516367316882,0.0
benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric2,1516367316882,0.0
benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric3,1516367316882,511.0
benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric4,1516367316882,0
benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric5,1516367316882,1.516367195446e+18
```

**Comment by joente** [comment]
I'm clueless, it works as expected on my system:
```
# benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric1
timestamp                    ┃ value
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━
Fri Jan 19 14:08:36 CET 2018 │ 0    

# benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric2
timestamp                    ┃ value
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━
Fri Jan 19 14:08:36 CET 2018 │ 0    

# benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric3
timestamp                    ┃ value
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━
Fri Jan 19 14:08:36 CET 2018 │ 511  

# benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric4
timestamp                    ┃ value
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━
Fri Jan 19 14:08:36 CET 2018 │ 0    

# benchmark_value1_10028_0.0_value2_1.0_0_10.0_-_OK_1.0_1.0_metric5
timestamp                    ┃ value             
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━
Fri Jan 19 14:08:36 CET 2018 │ 1.516367195446e+18
```

**Comment by thebuleon29** [comment]
Hi,
I reinstalled SiriDB and now it works. Whatever the problem was, I guess it was fixed in the last version. Thanks for your help.
